# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='bucket',
            field=models.CharField(default='EMPTY', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='extension',
            field=models.CharField(default='EMPTY', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='EMPTY', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='path',
            field=models.CharField(default='EMPTY', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
