# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import host.models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_auto_20160615_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.IntegerField(default=host.models.keygen, editable=False, primary_key=True, serialize=False),
        ),
    ]
