# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160312_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='looktype',
            field=models.CharField(choices=[('Driver', 'Driver'), ('Passenger', 'Passenger')], default=('Driver', 'Driver'), max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('Driver', 'Driver'), ('Passenger', 'Passenger')], default=('Driver', 'Driver'), max_length=200),
        ),
    ]
