# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160312_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='displayname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
