# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160312_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_dest', to='main.Location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='looktype',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_origin', to='main.Location'),
        ),
    ]
