# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160313_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(default='Trip 1', max_length=200),
            preserve_default=False,
        ),
    ]
