# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160313_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
