# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20160313_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='displayname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='joined',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='beh', max_length=200),
            preserve_default=False,
        ),
    ]
